###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.
developer-mode: false

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedregions
  password: unitedregions
  database: unitedregions

general:

  # Worlds where UnitedLands commands can be used
  worlds:
    - world

  new-day:
    # Start a new day at regular intervals instead of a fixed real-world time.
    use-interval: true
    # The length of one day (in seconds). Only used when use-new-day-interval is true
    interval-seconds: 3600
    # When use-new-day-interval is false, this will be the server time at which a new day 
    # starts. Must be hh:mm in 24-hour-format (e.g. 17:35)
    new-day-time: "00:00"

  # How long does a player need to be online in order add to their playtime (in seconds). If the time between logon and logoff is
  # less than this, their activity will not be logged and their playtime will not be increased.
  playtime-record-threshold: 60

  # Scale multiplier for the import SVG
  import-scale: 1
  # Offsets to be subtracted from the imported vertex positions. These will usually be
  # half of the map width / height
  import-offset-x: 0
  import-offset-y: 0

  region-chunk-size: 8
  # Colours as int values (e.g. https://argb-int-calculator.netlify.app/)

  protect-unclaimed-land: true

  allow-town-claims-outside-home-region: false

  # Default map colors & styles

  country-default-stroke-colour: -13399809
  country-default-fill-colour: 540248319
  country-default-stroke-width: 5

  region-default-stroke-colour: 536870912
  region-default-fill-colour: 0
  region-default-stroke-width: 2
  region-default-dash: "1"

  region-country-stroke-width: 1
  region-country-dash: "4,4"

  settlement-default-fill-colour: 540787967
  settlement-default-stroke-colour: -13399809
  settlement-default-stroke-width: 2
  settlement-default-dash: "1"

  settlement-country-stroke-colour: -1073741824
  settlement-country-fill-colour: 540248319
  settlement-country-stroke-width: 2
  settlement-country-dash: "4,4"



economy:
  new-settlement-cost: 8000
  settlement-claim-base-cost: 48
  settlement-base-upkeep-per-plot: 3

  # Available vars: base (base costs), claims (total settlement claim count).
  settlement-claim-cost-progression: "base"
  # Available vars: base (base costs), claims (total settlement claim count), residents (total resident count). This value will be multiplied by the number of settlement chunks.
  settlement-upkeep-per-plot-formula: "base * claims"

  settlement-tax-min-percent: 1.0
  settlement-tax-max-percent: 25.0
  settlement-tax-min-amount: 1.0
  settlement-tax-max-amount: 10000.0
  settlement-tax-cap: 10000.0

  new-country-cost: 80000

  region-claim-base-cost: 10000
  # The time (in seconds) between claiming a region and incorporating it into the country
  region-claim-time: 20
  # How many regions a country can claim in parallel
  region-parallel-claims-max: 1
  # base upkeep per region per day
  region-base-upkeep: 100
  # Available vars: base (base costs), modifier, regions (total country region count), distance (Euclidean distance to capital home chunk in blocks).
  region-claim-cost-formula: "base + (base * 0.1 * (distance / 512))"
  # Available vars: base (base costs), regions (total country region count), distance (Euclidean distance to capital home chunk in blocks).
  region-upkeep-formula: "base + (base * 0.1 * (distance / 512))"

protection:
  containers:
    - CHEST
    - TRAPPED_CHEST
    - ENDER_CHEST
    - BARREL
    - COPPER_CHEST
    - EXPOSED_COPPER_CHEST
    - WEATHERED_COPPER_CHEST
    - OXIDIZED_COPPER_CHEST
    - WAXED_COPPER_CHEST
    - WAXED_EXPOSED_COPPER_CHEST
    - WAXED_WEATHERED_COPPER_CHEST
    - WAXED_OXIDIZED_COPPER_CHEST
  use-blocks:
    - CRAFTING_TABLE
    - SMITHING_TABLE
    - ENCHANTING_TABLE
    - FLETCHING_TABLE
    - FURNACE
    - BLAST_FURNACE
    - CARTOGRAPHY_TABLE
    - BREWING_STAND
  switch-tags: # Minecraft material tags
    - doors
    - trapdoors
    - buttons
  switch-blocks:
    - LEVER
  interact:
    - VILLAGER
    - COW
    - SHEEP
  monsters:
    - ZOMBIE
    - ZOMBIE_VILLAGER
    - HUSK
    - SKELETON
    - CREEPER
    - SPIDER
    - CAVE_SPIDER
    - SLIME
    - PARCHED
    - DROWNED
    - PHANTOM
    - PILLAGER
    - RAVAGER
    - VINDICATOR
    - ENDERMAN
  animals:
    - CHICKEN
    - COW
    - SHEEP
    - PIG

settlement-chunks:
  none:
    map-icon: "+"
    map-icon-color: "§7"
    max-per-settlement: -1
  fortress:
    map-icon: "F"
    map-icon-color: "§f"
    max-per-settlement: 1



base_vanilla_potions_low_tier:
  timelimit: 7200
  random-descriptions:
    - ""
  order-items:
    terrain:
      materials:
        - POTION:SWIFTNESS
        - POTION:SLOWNESS
        - POTION:POISON
        - POTION:WEAKNESS
      unitsize: 1
      units: 4-27
      
base_custom_potions_low_tier:
  timelimit: 7200
  random-descriptions:
    - ""
  order-items:
    terrain:
      materials:
        - "hunger1"
        - "withering1"
        - "luck1"
        - "glowing1"
      unitsize: 1
      units: 4-27
      
splash_vanilla_potions_low_tier:
  timelimit: 7200
  random-descriptions:
    - ""
  order-items:
    terrain:
      materials:
        - SPLASH_POTION:SWIFTNESS
        - SPLASH_POTION:SLOWNESS
        - SPLASH_POTION:POISON
        - SPLASH_POTION:WEAKNESS
      unitsize: 1
      units: 4-27
      
splash_custom_potions_low_tier:
  timelimit: 7200
  random-descriptions:
    - ""
  order-items:
    terrain:
      materials:
        - "hunger4"
        - "withering4"
        - "luck3"
        - "glowing3"
      unitsize: 1
      units: 4-27
      
strong_potions_low_tier:
  timelimit: 7200
  random-descriptions:
    - ""
  order-items:
    terrain:
      materials:
        - POTION:STRONG_SWIFTNESS
        - POTION:STRONG_SLOWNESS
        - POTION:STRONG_POISON
        - "hunger2"
        - "withering2"
      unitsize: 1
      units: 4-27